services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      SERVE_UPLOADS_PUBLICLY: "false"
      UPLOAD_DIR: /var/www/one_cpk_data/uploads
    volumes:
      - /var/www/one_cpk_data/uploads:/var/www/one_cpk_data/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data:
